//auth Action Types
// Create

export const ACCOUNT_CREATION_SUCCESS = "ACCOUNT_CREATION_SUCCES";
export const ACCOUNT_CREATION_FAIL = "ACCOUNT_CREATION_FAIL";

//account details

export const ACCOUNT_DETAILS_SUCCESS = "ACCOUNT_DETAILS_SUCCESS";
export const ACCOUNT_DETAILS_FAIL = "ACCOUNT_DETAILS_FAIL";
