//auth Action Types
// Create
export const TRANSACTION_CREATION_SUCCESS = "TRANSACTION_CREATION_SUCCES";
export const TRANSACTION_CREATION_FAIL = "TRANSACTION_CREATION_FAIL";

//Update
export const TRANSACTION_UPDATE_SUCCESS = "TRANSACTION_UPDATE_SUCCES";
export const TRANSACTION_UPDATE_FAIL = "TRANSACTION_UPDATE_FAIL";

//Delete
export const TRANSACTION_DELETE_SUCCESS = "TRANSACTION_DELETE_SUCCES";
export const TRANSACTION_DELETE_FAIL = "TRANSACTION_DELETE_FAIL";
